export default [
  {
    id: 1,
    title: "Frontend Developer",
    type: "Full time",
    location: "Remote",
    companyName: "Google",
    skills: ["Javascript", "ReactJs", "NodeJs"],
  },
  {
    id: 2,
    title: "Flutter Developer",
    type: "Part time",
    location: "Hybrid",
    companyName: "Microsoft",
    skills: ["Dart", "Flutter", "Bloc"],
  },
  {
    id: 3,
    title: "React Native Developer",
    type: "Full time",
    location: "Remote",
    companyName: "Google",
    skills: ["Bloc", "ReactJs", "NodeJs"],
  },
  {
    id: 4,
    title: "Network Engineer",
    type: "Part time",
    location: "Hybrid",
    companyName: "Microsoft",
    skills: ["DSA", "C++", "Computer networking"],
  },
  {
    id: 5,
    title: "UI/UX Developer",
    type: "Full time",
    location: "Work from Home",
    companyName: "Oracle",
    skills: ["Figma", "Adobe XD"],
  },
  {
    id: 6,
    title: "Software Developer",
    type: "Full time",
    location: "Hybrid",
    companyName: "Meta",
    skills: ["Dart", "C#", "Bloc"],
  },
  {
    id: 7,
    title: "Product Manager",
    type: "Full time",
    location: "Remote",
    companyName: "Google",
    skills: ["Python", "ReactJs", "NodeJs"],
  },
  {
    id: 8,
    title: "AI/ML Engineer",
    type: "Part time",
    location: "Hybrid",
    companyName: "saleforce",
    skills: ["DSA", "C++", "ML Algorithms"],
  },
];
